### ISSUE TITLE
al.exe missing on sdk 4.8

### ISSUE THREAD

**Issue by RMarinaro** [microsoft/dotnet-framework-docker#313]
Trying to build a project that relies on the build tools on the 4.8 images throws an error:

```
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3628,5): error MSB3086: Task could not find "al.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed [C:\codebuild\tmp\output\src323577031\vendor-portals\BCS.VendorPortals\BCS.VendorPortals.Core\BCS.VendorPortals.Core.vbproj] 
Done Building Project "C:\codebuild\tmp\output\src323577031\vendor-portals\BCS.VendorPortals\BCS.VendorPortals.Core\BCS.VendorPortals.Core.vbproj" (default targets) -- FAILED. 
Done Building Project "C:\codebuild\tmp\output\src323577031\vendor-portals\BCS.VendorPortals\BCS.VendorPortals.WebApp\BCS.VendorPortals.WebApp.vbproj" (DeployOnServer target(s)) -- FAILED. 
```

It looks like it is trying to look for the SDK tools in the 4.7.2 directory instead of 4.8.  Reverting the SDK image to 4.7.2 fixed the build

I think this is related to https://github.com/microsoft/dotnet-framework-docker/pull/169

**Comment by mthalman** [comment]
I believe this is related to #214, but in the context of 4.8 instead of 4.7.2.

**Comment by MichaelSimons** [comment]
Assigning to @mthalman, to investigate.

**Comment by Smenus** [comment]
I have my own version of the sdk image, because we needed to add a few extra things during the Build Tools install.
I've added this line to the end of the SDK install bit, and it does mean that the .exes from the 4.8 SDK are found by msbuild...
```powershell
	&& powershell -Command "$ErrorActionPreference = 'Stop'; (Get-Content '%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe.config' -Encoding UTF8) -replace 'NETFXSDK\\4\.7\.2', 'NETFXSDK\4.8' | Set-Content '%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe.config' -Encoding UTF8"
```
Not the prettiest work around, but it did work!

**Comment by mthalman** [comment]
See #326 for a repro project.

**Comment by mthalman** [comment]
@rainersigwald -  I'm pretty sure this problem stems from SDK40ToolsPath being set to a 4.7.2 registry path in the MSBuild.exe.config.  Same sort of issue as #214. Do you know whether this path would be updated when 4.8 is available for install in the VS Build Tools?  Or is it completely unrelated to that?

**Comment by mthalman** [comment]
I've verified that installing 4.7.2 in the SDK image fixes the problem.  Interestingly, doing this _decreases_ the size of the image by 33 MB.  The layer that installs the SDK gets larger but some of the downstream layers get smaller with an overall net loss.

**Comment by mthalman** [comment]
> I've verified that installing 4.7.2 in the SDK image fixes the problem. Interestingly, doing this _decreases_ the size of the image by 33 MB. The layer that installs the SDK gets larger but some of the downstream layers get smaller with an overall net loss.

I take that back.  I had things misconfigured in this analysis.  Installing 4.7.2 in the SDK image results in an image that is 11.3 MB larger.

**Comment by rainersigwald** [comment]
This is exactly the same as #214, except that the default moved from 4.6.1 (Visual Studio 2017) to 4.7.2 (Visual Studio 2019 16.0, 16.1, 16.2, but _with bugs_ that mean that you probably _also_ want 4.6.1 installed 😬).

For the forthcoming 16.3, the default is moving to 4.8 (microsoft/msbuild#4487, cc @tmeschter), and hopefully we'll have enough lead time to fix up some of the bugs so installing only that should be fine.

**Comment by GammaFour** [comment]
Just installed 16.3.  Getting the error:
`error MSB3086: Task could not find "al.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.7.2\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed
`When everything worked just great before the upgrade.

**Comment by GammaFour** [comment]
I uninstalled the 16.3.0 Upgrade and then re-installed 16.3.0 from scratch.  Same error.  I had to download the .NET Framework 4.7.2 SDK to make the error messages go away.  If you have a dependency on 4.7.2 SDK in Visual Studio 2019, why don't you just bake it into the install package?

**Comment by rainersigwald** [comment]
@gammafour are you hitting that in a Docker image built from this repo, or on a machine you installed in other ways?

**Comment by mthalman** [comment]
This should be fixed with the latest 4.8 SDK image that was just published.  It installs VS 16.3 tools.

**Comment by wli3** [comment]
I am using mcr.microsoft.com/dotnet/framework/sdk:4.8-windowsservercore-ltsc2019 I still see this issue. @mthalman it is latest enough?

**Comment by wli3** [comment]
Just pulled the image

**Comment by mthalman** [comment]
This is still an issue.  The cause of it is microsoft/msbuild#4782.  As a workaround, the `Microsoft.Net.Component.4.7.2.SDK` component can be installed from Build Tools ([example](https://github.com/microsoft/dotnet-framework-docker/blob/ae91b6daeb13152ecbe7fbabfef9c95a5423333d/4.7.2/sdk/windowsservercore-ltsc2019/Dockerfile#L26)).

**Comment by xamarindevelopervietnam** [comment]
just reinstalled windows and vs 16.3.2, got same error. Did it fix?

**Comment by mthalman** [comment]
> just reinstalled windows and vs 16.3.2, got same error. Did it fix?

As I mentioned in my previous comment, the issue is not fixed.  The workaround is to manually install the `Microsoft.Net.Component.4.7.2.SDK` component.

Here's an example of doing that:
```
# Install 4.7.2 SDK
RUN `
    # Install VS Build Tools
    && curl -fSLo vs_BuildTools.exe https://download.visualstudio.microsoft.com/download/pr/1d102ee6-9263-4353-8676-6430f0cc5998/c0457643c8a80b008250148151a51cb6cc0aa2ccb57316db496628faa9b9a84f/vs_BuildTools.exe `
    && start /w vs_BuildTools.exe ^ `
       modify ^ `
       --installPath "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\BuildTools" ^ `
       --add Microsoft.Net.Component.4.7.2.SDK ^ `
       --quiet --norestart --nocache --wait `
    && del vs_BuildTools.exe `
    `
    # Cleanup
    && rmdir /S /Q "%ProgramFiles(x86)%\Microsoft Visual Studio\Installer" `
    && powershell Remove-Item -Force -Recurse "%TEMP%\*"
```

**Comment by xamarindevelopervietnam** [comment]
thanks @mthalman I install .Net 4.7.2 SDK and issue fixed

**Comment by basslagter** [comment]
Installing Microsoft.Net.Component.4.7.2.SDK from the Visual Studio installer fixed it for me!

**Comment by pablos91** [comment]
OMG! @basslagter installing SDK 4.7.2 from VS installer resolved my issue. I have searched for this for 2 days and found your answer THANKS

**Comment by DRAirey1** [comment]
> 4.8 SDK

It was not fixed.  The only way I've gotten around this error is to install the SDK 4.7.2.  Please fix the issue.

**Comment by mthalman** [comment]
> > 4.8 SDK
> 
> It was not fixed. The only way I've gotten around this error is to install the SDK 4.7.2. Please fix the issue. This error occurs on a virgin machine, with a fresh download of VS 2019 16.3 Community Edition so it really shouldn't be that difficult to reproduce.

@DRAirey1 - Correct, it's already been acknowledged that this isn't fixed.  The underlying issue is https://github.com/microsoft/msbuild/issues/4782.

**Comment by cetintas41** [comment]
Install Microsoft.Net.Component.4.7.2.SDK via VS Installer.

**Comment by mthalman** [comment]
This is fixed in the latest images: https://github.com/microsoft/dotnet-framework-docker/pull/465

**Comment by CZEMacLeod** [comment]
@mthalman - Looks like this issue has reoccurred with the new 4.8.1 sdk images (e.g. mcr.microsoft.com/dotnet/framework/sdk:4.8.1-20220913-windowsservercore-ltsc2022)
Getting 
```
##[error]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3873,5): Error MSB3086: Task could not find "al.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed
```

**Comment by mthalman** [comment]
> @mthalman - Looks like this issue has reoccurred with the new 4.8.1 sdk images (e.g. mcr.microsoft.com/dotnet/framework/sdk:4.8.1-20220913-windowsservercore-ltsc2022) Getting
> 
> ```
> ##[error]C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3873,5): Error MSB3086: Task could not find "al.exe" using the SdkToolsPath "" or the registry key "HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\NETFXSDK\4.8\WinSDK-NetFx40Tools-x86". Make sure the SdkToolsPath is set and the tool exists in the correct processor specific location under the SdkToolsPath and that the Microsoft Windows SDK is installed
> ```

@CZEMacLeod - Thanks for letting me know! I've logged an issue for this at https://github.com/dotnet/msbuild/issues/8027.
